version: 2.1

jobs:
  main:
    machine:
      image: ubuntu-2004:202010-01 # recommended linux image
    resource_class: 2xlarge
    steps:
      - checkout
      - run:
          name: Build OS Image
          no_output_timeout: 1h
          command: |
              docker run --privileged -i -v /proc:/proc \
              -v ${PWD}:/working_dir \
              -w /working_dir \
              debian:latest \
              /bin/bash -s etc/terraform-daily-6.1-azure.conf < build.sh
              cd builds/*/
              sudo chmod -R 0777 .
              sudo chmod 0777 *            
              sudo mkdir -p /tmp/build-artifacts/
              sudo mv $(find | grep -i iso) /tmp/build-artifacts/

      - store_artifacts:
          path: /tmp/build-artifacts/
# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  build:
    jobs:
      - main
